#!/bin/sh
#
# musl-clang: A clang wrapper for musl C library.
#             Supports static linking. (-static)
#
# WARNING: This is not a perfect drop-in replacement
#
# See LICENSE file for copyright and license details.
#

PREFIX=${MUSL_PREFIX:-"/usr/local/musl"}
if [ ! -d "${PREFIX}" ]; then
	echo "invalid prefix: ${PREFIX}"
	return 1
fi

CLANG=${REALCLANG:-"clang"}

hasNo() {
	pat="$1"
	shift 1

	for e in "$@"; do
		if [ "$e" = "${pat}" ]; then
			return 1
		fi
	done
	return 0
}

ARGS="-nostdinc -isystem ${PREFIX}/include"
TAIL=""

if \
	hasNo '-c' "$@" && \
	hasNo '-S' "$@" && \
	hasNo '-E' "$@"
then
	ARGS="${ARGS} -nostdlib"
	ARGS="${ARGS} -Wl,-dynamic-linker ${PREFIX}/lib/libc.so"
	ARGS="${ARGS} -L${PREFIX}/lib"

	TAIL="${TAIL} ${PREFIX}/lib/crt1.o"
	TAIL="${TAIL} ${PREFIX}/lib/crti.o"
	TAIL="${TAIL} ${PREFIX}/lib/crtn.o"
	TAIL="${TAIL} -lc"
	# you might want this
	#TAIL="${TAIL} -lcompiler_rt"
fi

exec ${CLANG} ${ARGS} "$@" ${TAIL}

